# Site settings
# Name of your blog (this will show up at the top of your page and in the RSS feed)
title: CFW STEM Committee

# Your email if you want it to be linked on the contact page
email: cfwstem@utk.edu

description: > # this means to ignore newlines until "baseurl:"
  Group of highly motivated male, female, and ally students at the undergraduate and graduate levels
  focused on improving the status and representation of women in science, technology, engineering, and math fields at the University of Tennessee.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cfwstem.github.io" # the base hostname & protocol for your site
twitter_username: utkcfwstem
#github_username:  cfwstem
facebook_username: utkcfwstem

# Build settings
markdown: kramdown
